// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAec1fkeanHaSjAj5JyJI_ZP6tpj1mZ1Lw',
    appId: '1:1058462303291:web:5ef2504eaf2c2ea2e1481e',
    messagingSenderId: '1058462303291',
    projectId: 'grocerappflutter',
    authDomain: 'grocerappflutter.firebaseapp.com',
    storageBucket: 'grocerappflutter.appspot.com',
    measurementId: 'G-JCMZ8VF57C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGrC9W2knzz6KjShf2Wi2cTaIcrOVSVUA',
    appId: '1:1058462303291:android:8c7cee57d6e5d5bfe1481e',
    messagingSenderId: '1058462303291',
    projectId: 'grocerappflutter',
    storageBucket: 'grocerappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHzVVdLxryIkQD52OKSS6DgqnHVsFcVk',
    appId: '1:1058462303291:ios:e0226798d3867963e1481e',
    messagingSenderId: '1058462303291',
    projectId: 'grocerappflutter',
    storageBucket: 'grocerappflutter.appspot.com',
    iosClientId: '1058462303291-h4386lnbs842euqr1bvblcb034qes295.apps.googleusercontent.com',
    iosBundleId: 'com.example.groccerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHzVVdLxryIkQD52OKSS6DgqnHVsFcVk',
    appId: '1:1058462303291:ios:e0226798d3867963e1481e',
    messagingSenderId: '1058462303291',
    projectId: 'grocerappflutter',
    storageBucket: 'grocerappflutter.appspot.com',
    iosClientId: '1058462303291-h4386lnbs842euqr1bvblcb034qes295.apps.googleusercontent.com',
    iosBundleId: 'com.example.groccerApp',
  );
}
